FROM nginx:1.26-alpine
RUN rm /etc/nginx/conf.d/default.conf

# 설정 파일 복사
COPY default.conf /etc/nginx/conf.d/default.conf

# HTML 파일 복사 (경로 수정: ./html/ 폴더 참조)
COPY ./html/index.html /usr/share/nginx/html/index.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]